services:
  flask-app:
    build: .
    container_name: flask_app_container
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devfood
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev1234
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
